apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
spec:
  type: NodePort          # or LoadBalancer if using cloud (like AWS/GKE)
  selector:
    app: myapp            # must match the label in deployment.yml
  ports:
    - port: 8080          # service port
      targetPort: 8080    # container port

